apiVersion: v1
kind: Service
metadata:
  name: rgw-usage-exporter
  labels:
    app: rgw-usage-exporter
spec:
  selector:
    app: rgw-usage-exporter
  ports:
  - name: metrics
    port: 9099
    targetPort: metrics
