name: Build and Push

on:
  schedule:
  - cron: '0 0 * * 0'
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on:
      group: Default
    permissions:
      contents: read
      packages: read
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

    - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
      if: github.ref == 'refs/heads/main'
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
      with:
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: |
          ${{ vars.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ vars.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
